.PHONY: provider schema codegen clean

VERSION ?= 0.2.0

provider:
	mkdir -p bin
	go build -o bin/pulumi-resource-resend ./provider/cmd/pulumi-resource-resend

schema: provider
	pulumi package get-schema ./bin/pulumi-resource-resend | jq 'del(.version)' > provider/cmd/pulumi-resource-resend/schema.json

codegen: schema
	pulumi package gen-sdk ./bin/pulumi-resource-resend --language nodejs --out sdk
	@# Patch generated SDK files that codegen overwrites with defaults
	cd sdk/nodejs && \
		jq --arg v "$(VERSION)" '. * { \
			"name": "@humanlayer/pulumi-resend", \
			"version": $$v, \
			"description": "A Pulumi provider for managing Resend email resources", \
			"keywords": ["pulumi","resend","email","infrastructure-as-code"], \
			"homepage": "https://github.com/humanlayer/pulumi-resend", \
			"repository": {"type":"git","url":"https://github.com/humanlayer/pulumi-resend.git"}, \
			"license": "MIT", \
			"publishConfig": {"access":"public"}, \
			"pulumi": (.pulumi * {"server":"github://api.github.com/humanlayer/pulumi-resend"}) \
		}' package.json > package.json.tmp && mv package.json.tmp package.json
	@# functions/index.ts is generated empty which breaks TypeScript imports
	@echo '// *** WARNING: this file was generated by pulumi-language-nodejs. ***' > sdk/nodejs/functions/index.ts
	@echo '// *** Do not edit by hand unless you are certain you know what you are doing! ***' >> sdk/nodejs/functions/index.ts
	@echo '' >> sdk/nodejs/functions/index.ts
	@echo 'export {};' >> sdk/nodejs/functions/index.ts
	@# Copy root README into the SDK package
	cp README.md sdk/nodejs/README.md

clean:
	rm -rf bin
