.PHONY: provider schema codegen clean

VERSION ?= 0.2.0

provider:
	mkdir -p bin
	go build -o bin/pulumi-resource-resend ./provider/cmd/pulumi-resource-resend

schema: provider
	pulumi package get-schema ./bin/pulumi-resource-resend | jq 'del(.version)' > provider/cmd/pulumi-resource-resend/schema.json

codegen: schema
	pulumi package gen-sdk ./bin/pulumi-resource-resend --language nodejs --out sdk
	@# Patch package.json: merge publish metadata and set version
	cd sdk/nodejs && \
		jq -s --arg v "$(VERSION)" '.[0] * .[1] * {"version":$$v} * {"pulumi":(.[0].pulumi * {"server":"github://api.github.com/humanlayer/pulumi-resend"})}' \
		package.json ../package.patch.json > package.json.tmp && mv package.json.tmp package.json
	@# functions/index.ts is generated empty which breaks TypeScript imports
	@printf '%s\n' \
		'// *** WARNING: this file was generated by pulumi-language-nodejs. ***' \
		'// *** Do not edit by hand unless you are certain you know what you are doing! ***' \
		'' \
		'export {};' > sdk/nodejs/functions/index.ts
	@# Copy root README into the SDK package
	cp README.md sdk/nodejs/README.md

clean:
	rm -rf bin
