// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// This file is intentionally empty but must export something for TypeScript module compatibility.
export {};
