// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace functions {
    /**
     * An email attachment.
     */
    export interface Attachment {
        /**
         * Base64-encoded content of the attachment.
         */
        content?: string;
        /**
         * Content ID for inline attachments (e.g., for embedding images in HTML).
         */
        contentId?: string;
        /**
         * The MIME type of the attachment.
         */
        contentType?: string;
        /**
         * The filename of the attachment.
         */
        filename: string;
        /**
         * URL path to fetch the attachment content from.
         */
        path?: string;
    }

    /**
     * An email attachment.
     */
    export interface AttachmentArgs {
        /**
         * Base64-encoded content of the attachment.
         */
        content?: pulumi.Input<string>;
        /**
         * Content ID for inline attachments (e.g., for embedding images in HTML).
         */
        contentId?: pulumi.Input<string>;
        /**
         * The MIME type of the attachment.
         */
        contentType?: pulumi.Input<string>;
        /**
         * The filename of the attachment.
         */
        filename: pulumi.Input<string>;
        /**
         * URL path to fetch the attachment content from.
         */
        path?: pulumi.Input<string>;
    }

    /**
     * An email tag for categorization.
     */
    export interface Tag {
        /**
         * The tag name.
         */
        name: string;
        /**
         * The tag value.
         */
        value: string;
    }

    /**
     * An email tag for categorization.
     */
    export interface TagArgs {
        /**
         * The tag name.
         */
        name: pulumi.Input<string>;
        /**
         * The tag value.
         */
        value: pulumi.Input<string>;
    }
}

export namespace resources {
    /**
     * A connection (edge) between steps in a Resend automation workflow.
     */
    export interface AutomationConnectionArgs {
        /**
         * The key of the source step.
         */
        from: pulumi.Input<string>;
        /**
         * The key of the destination step.
         */
        to: pulumi.Input<string>;
        /**
         * The connection type: default, condition_met, condition_not_met, timeout, or event_received. Defaults to 'default'.
         */
        type?: pulumi.Input<string>;
    }

    /**
     * A step in a Resend automation workflow.
     */
    export interface AutomationStepArgs {
        /**
         * Configuration object for the step. Structure depends on the step type.
         */
        config: pulumi.Input<{[key: string]: any}>;
        /**
         * Unique identifier for this step within the automation. Used to reference the step in connections.
         */
        key: pulumi.Input<string>;
        /**
         * The type of step: trigger, send_email, delay, wait_for_event, condition, contact_update, contact_delete, or add_to_segment.
         */
        type: pulumi.Input<string>;
    }

    /**
     * A Resend template variable definition.
     */
    export interface TemplateVariableArgs {
        /**
         * Optional fallback value used when no value is supplied.
         */
        fallbackValue?: pulumi.Input<string>;
        /**
         * The template variable key.
         */
        key: pulumi.Input<string>;
        /**
         * The template variable type, such as string, number, boolean, object, or list.
         */
        type: pulumi.Input<string>;
    }
}
