// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    /**
     * A DNS record required to verify or operate a Resend domain.
     */
    export interface DnsRecord {
        /**
         * The DNS record name.
         */
        name: string;
        /**
         * The MX priority for records that require one.
         */
        priority?: number;
        /**
         * The Resend record purpose, such as SPF, DKIM, Receiving, Tracking, or TrackingCAA.
         */
        record: string;
        /**
         * The verification status of the DNS record.
         */
        status: string;
        /**
         * The DNS record time-to-live value.
         */
        ttl: string;
        /**
         * The DNS record type, such as TXT, MX, CNAME, or CAA.
         */
        type: string;
        /**
         * The DNS record value.
         */
        value: string;
    }

}
