// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace functions {
}

export namespace resources {
    /**
     * A connection (edge) between steps in a Resend automation workflow.
     */
    export interface AutomationConnection {
        /**
         * The key of the source step.
         */
        from: string;
        /**
         * The key of the destination step.
         */
        to: string;
        /**
         * The connection type: default, condition_met, condition_not_met, timeout, or event_received. Defaults to 'default'.
         */
        type?: string;
    }

    /**
     * A step in a Resend automation workflow.
     */
    export interface AutomationStep {
        /**
         * Configuration object for the step. Structure depends on the step type.
         */
        config: {[key: string]: any};
        /**
         * Unique identifier for this step within the automation. Used to reference the step in connections.
         */
        key: string;
        /**
         * The type of step: trigger, send_email, delay, wait_for_event, condition, contact_update, contact_delete, or add_to_segment.
         */
        type: string;
    }

    /**
     * A DNS record required to verify or operate a Resend domain.
     */
    export interface DnsRecord {
        /**
         * The DNS record name.
         */
        name: string;
        /**
         * The MX priority for records that require one.
         */
        priority?: number;
        /**
         * The Resend record purpose, such as SPF, DKIM, Receiving, Tracking, or TrackingCAA.
         */
        record: string;
        /**
         * The verification status of the DNS record.
         */
        status: string;
        /**
         * The DNS record time-to-live value.
         */
        ttl: string;
        /**
         * The DNS record type, such as TXT, MX, CNAME, or CAA.
         */
        type: string;
        /**
         * The DNS record value.
         */
        value: string;
    }

    /**
     * A Resend template variable definition.
     */
    export interface TemplateVariable {
        /**
         * Optional fallback value used when no value is supplied.
         */
        fallbackValue?: string;
        /**
         * The template variable key.
         */
        key: string;
        /**
         * The template variable type, such as string, number, boolean, object, or list.
         */
        type: string;
    }

}
