// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Resend API key. API key changes are replaced because Resend does not support updates.
 */
export class ApiKey extends pulumi.CustomResource {
    /**
     * Get an existing ApiKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ApiKey {
        return new ApiKey(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:ApiKey';

    /**
     * Returns true if the given object is an instance of ApiKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApiKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApiKey.__pulumiType;
    }

    /**
     * Timestamp when the API key was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional domain ID that restricts this API key to a single domain.
     */
    declare public readonly domainId: pulumi.Output<string | undefined>;
    /**
     * Timestamp when the API key was last used, if any.
     */
    declare public /*out*/ readonly lastUsedAt: pulumi.Output<string | undefined>;
    /**
     * Display name for the API key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * API key permission: full_access or sending_access.
     */
    declare public readonly permission: pulumi.Output<string | undefined>;
    /**
     * Secret API key token returned only when the key is created.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a ApiKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiKeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["domainId"] = args?.domainId;
            resourceInputs["name"] = args?.name;
            resourceInputs["permission"] = (args?.permission) ?? "full_access";
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["lastUsedAt"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["lastUsedAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["permission"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ApiKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ApiKey resource.
 */
export interface ApiKeyArgs {
    /**
     * Optional domain ID that restricts this API key to a single domain.
     */
    domainId?: pulumi.Input<string>;
    /**
     * Display name for the API key.
     */
    name: pulumi.Input<string>;
    /**
     * API key permission: full_access or sending_access.
     */
    permission?: pulumi.Input<string>;
}
