// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Resend automation for email automation workflows. Automations allow you to create multi-step email sequences triggered by events.
 */
export class Automation extends pulumi.CustomResource {
    /**
     * Get an existing Automation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Automation {
        return new Automation(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Automation';

    /**
     * Returns true if the given object is an instance of Automation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Automation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Automation.__pulumiType;
    }

    /**
     * The connections (edges) between steps defining the workflow graph.
     */
    declare public readonly connections: pulumi.Output<outputs.resources.AutomationConnection[]>;
    /**
     * Timestamp when the automation was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The name of the automation.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The automation status: 'enabled' or 'disabled'. Defaults to 'disabled'.
     */
    declare public readonly status: pulumi.Output<string | undefined>;
    /**
     * The steps in the automation workflow. Must contain 1-150 steps, including at least one trigger step.
     */
    declare public readonly steps: pulumi.Output<outputs.resources.AutomationStep[]>;
    /**
     * Timestamp when the automation was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Automation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AutomationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.connections === undefined && !opts.urn) {
                throw new Error("Missing required property 'connections'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.steps === undefined && !opts.urn) {
                throw new Error("Missing required property 'steps'");
            }
            resourceInputs["connections"] = args?.connections;
            resourceInputs["name"] = args?.name;
            resourceInputs["status"] = args?.status;
            resourceInputs["steps"] = args?.steps;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        } else {
            resourceInputs["connections"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["steps"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Automation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Automation resource.
 */
export interface AutomationArgs {
    /**
     * The connections (edges) between steps defining the workflow graph.
     */
    connections: pulumi.Input<pulumi.Input<inputs.resources.AutomationConnectionArgs>[]>;
    /**
     * The name of the automation.
     */
    name: pulumi.Input<string>;
    /**
     * The automation status: 'enabled' or 'disabled'. Defaults to 'disabled'.
     */
    status?: pulumi.Input<string>;
    /**
     * The steps in the automation workflow. Must contain 1-150 steps, including at least one trigger step.
     */
    steps: pulumi.Input<pulumi.Input<inputs.resources.AutomationStepArgs>[]>;
}
