// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Resend contact property for defining custom fields on contacts. Contact properties allow you to store additional data about your contacts.
 */
export class ContactProperty extends pulumi.CustomResource {
    /**
     * Get an existing ContactProperty resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ContactProperty {
        return new ContactProperty(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:ContactProperty';

    /**
     * Returns true if the given object is an instance of ContactProperty.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContactProperty {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContactProperty.__pulumiType;
    }

    /**
     * Timestamp when the contact property was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional fallback value used when the property is not set on a contact.
     */
    declare public readonly fallbackValue: pulumi.Output<string | undefined>;
    /**
     * The key of the contact property. Must be alphanumeric with underscores only, maximum 50 characters. This field is immutable after creation.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * The type of the contact property: string or number. This field is immutable after creation.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a ContactProperty resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContactPropertyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["fallbackValue"] = args?.fallbackValue;
            resourceInputs["key"] = args?.key;
            resourceInputs["type"] = args?.type;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fallbackValue"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContactProperty.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ContactProperty resource.
 */
export interface ContactPropertyArgs {
    /**
     * Optional fallback value used when the property is not set on a contact.
     */
    fallbackValue?: pulumi.Input<string>;
    /**
     * The key of the contact property. Must be alphanumeric with underscores only, maximum 50 characters. This field is immutable after creation.
     */
    key: pulumi.Input<string>;
    /**
     * The type of the contact property: string or number. This field is immutable after creation.
     */
    type: pulumi.Input<string>;
}
