// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Resend sending domain with DNS records for verification and routing.
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * Enabled domain capabilities. Supported values are sending and receiving.
     */
    declare public readonly capabilities: pulumi.Output<string[] | undefined>;
    /**
     * Whether Resend should track link clicks for this domain.
     */
    declare public readonly clickTracking: pulumi.Output<boolean | undefined>;
    /**
     * Timestamp when the domain was created in Resend.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional custom return-path subdomain for bounce handling.
     */
    declare public readonly customReturnPath: pulumi.Output<string | undefined>;
    /**
     * The domain name to manage in Resend.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether Resend should track email opens for this domain.
     */
    declare public readonly openTracking: pulumi.Output<boolean | undefined>;
    /**
     * DNS records Resend requires for domain verification and operation.
     */
    declare public /*out*/ readonly records: pulumi.Output<outputs.resources.DnsRecord[]>;
    /**
     * The Resend sending region for the domain, such as us-east-1, eu-west-1, sa-east-1, or ap-northeast-1.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * The current Resend verification status for the domain.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * TLS mode for email delivery: opportunistic or enforced.
     */
    declare public readonly tls: pulumi.Output<string | undefined>;
    /**
     * Optional subdomain to use for click and open tracking.
     */
    declare public readonly trackingSubdomain: pulumi.Output<string | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["capabilities"] = args?.capabilities;
            resourceInputs["clickTracking"] = args?.clickTracking;
            resourceInputs["customReturnPath"] = args?.customReturnPath;
            resourceInputs["name"] = args?.name;
            resourceInputs["openTracking"] = args?.openTracking;
            resourceInputs["region"] = args?.region;
            resourceInputs["tls"] = args?.tls;
            resourceInputs["trackingSubdomain"] = args?.trackingSubdomain;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["records"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["capabilities"] = undefined /*out*/;
            resourceInputs["clickTracking"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["customReturnPath"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["openTracking"] = undefined /*out*/;
            resourceInputs["records"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["tls"] = undefined /*out*/;
            resourceInputs["trackingSubdomain"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * Enabled domain capabilities. Supported values are sending and receiving.
     */
    capabilities?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether Resend should track link clicks for this domain.
     */
    clickTracking?: pulumi.Input<boolean>;
    /**
     * Optional custom return-path subdomain for bounce handling.
     */
    customReturnPath?: pulumi.Input<string>;
    /**
     * The domain name to manage in Resend.
     */
    name: pulumi.Input<string>;
    /**
     * Whether Resend should track email opens for this domain.
     */
    openTracking?: pulumi.Input<boolean>;
    /**
     * The Resend sending region for the domain, such as us-east-1, eu-west-1, sa-east-1, or ap-northeast-1.
     */
    region?: pulumi.Input<string>;
    /**
     * TLS mode for email delivery: opportunistic or enforced.
     */
    tls?: pulumi.Input<string>;
    /**
     * Optional subdomain to use for click and open tracking.
     */
    trackingSubdomain?: pulumi.Input<string>;
}
