// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Resend event for defining custom event types that trigger automations. Events allow you to send behavioral data about contacts to trigger automated email sequences.
 */
export class Event extends pulumi.CustomResource {
    /**
     * Get an existing Event resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Event {
        return new Event(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Event';

    /**
     * Returns true if the given object is an instance of Event.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Event {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Event.__pulumiType;
    }

    /**
     * Timestamp when the event was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The name of the event. Must not start with 'resend:' (reserved prefix). This field is immutable after creation.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Optional schema defining the event payload structure. Maps field names to types: string, number, boolean, or date.
     */
    declare public readonly schema: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Timestamp when the event was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Event resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["schema"] = args?.schema;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["schema"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Event.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Event resource.
 */
export interface EventArgs {
    /**
     * The name of the event. Must not start with 'resend:' (reserved prefix). This field is immutable after creation.
     */
    name: pulumi.Input<string>;
    /**
     * Optional schema defining the event payload structure. Maps field names to types: string, number, boolean, or date.
     */
    schema?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
