// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiKeyArgs } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { DomainArgs } from "./domain";
export type Domain = import("./domain").Domain;
export const Domain: typeof import("./domain").Domain = null as any;
utilities.lazyLoad(exports, ["Domain"], () => require("./domain"));

export { DomainVerificationArgs } from "./domainVerification";
export type DomainVerification = import("./domainVerification").DomainVerification;
export const DomainVerification: typeof import("./domainVerification").DomainVerification = null as any;
utilities.lazyLoad(exports, ["DomainVerification"], () => require("./domainVerification"));

export { EventArgs } from "./event";
export type Event = import("./event").Event;
export const Event: typeof import("./event").Event = null as any;
utilities.lazyLoad(exports, ["Event"], () => require("./event"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SendEmailArgs, SendEmailResult, SendEmailOutputArgs } from "./sendEmail";
export const sendEmail: typeof import("./sendEmail").sendEmail = null as any;
export const sendEmailOutput: typeof import("./sendEmail").sendEmailOutput = null as any;
utilities.lazyLoad(exports, ["sendEmail","sendEmailOutput"], () => require("./sendEmail"));

export { TemplateArgs } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));

export { TopicArgs } from "./topic";
export type Topic = import("./topic").Topic;
export const Topic: typeof import("./topic").Topic = null as any;
utilities.lazyLoad(exports, ["Topic"], () => require("./topic"));

export { WebhookArgs } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));


// Export sub-modules:
import * as config from "./config";
import * as functions from "./functions";
import * as types from "./types";

export {
    config,
    functions,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "resend:index:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "resend:index:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "resend:index:DomainVerification":
                return new DomainVerification(name, <any>undefined, { urn })
            case "resend:index:Event":
                return new Event(name, <any>undefined, { urn })
            case "resend:index:Template":
                return new Template(name, <any>undefined, { urn })
            case "resend:index:Topic":
                return new Topic(name, <any>undefined, { urn })
            case "resend:index:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("resend", "index", _module)
pulumi.runtime.registerResourcePackage("resend", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:resend") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
