// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Create and send a broadcast email to a segment via the Resend API. This combines broadcast creation and sending into a single atomic operation using the send: true flag.
 */
export function sendBroadcast(args: SendBroadcastArgs, opts?: pulumi.InvokeOptions): Promise<SendBroadcastResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("resend:index:sendBroadcast", {
        "from": args.from,
        "html": args.html,
        "name": args.name,
        "previewText": args.previewText,
        "replyTo": args.replyTo,
        "scheduledAt": args.scheduledAt,
        "segmentId": args.segmentId,
        "subject": args.subject,
        "text": args.text,
        "topicId": args.topicId,
    }, opts);
}

export interface SendBroadcastArgs {
    /**
     * The sender email address. Must be a verified domain.
     */
    from: string;
    /**
     * The HTML body of the broadcast email.
     */
    html?: string;
    /**
     * An optional name for the broadcast (for internal reference).
     */
    name?: string;
    /**
     * Preview text shown in email clients before opening the email.
     */
    previewText?: string;
    /**
     * List of reply-to email addresses.
     */
    replyTo?: string[];
    /**
     * ISO 8601 timestamp to schedule the broadcast for future delivery. Omit for immediate send.
     */
    scheduledAt?: string;
    /**
     * The ID of the segment to send the broadcast to.
     */
    segmentId: string;
    /**
     * The email subject line for the broadcast.
     */
    subject: string;
    /**
     * The plain text body of the broadcast email.
     */
    text?: string;
    /**
     * Topic ID for managing unsubscribes.
     */
    topicId?: string;
}

export interface SendBroadcastResult {
    /**
     * The unique identifier for the broadcast.
     */
    readonly broadcastId: string;
    /**
     * The status of the broadcast (e.g., 'queued' or 'sent').
     */
    readonly status: string;
}
/**
 * Create and send a broadcast email to a segment via the Resend API. This combines broadcast creation and sending into a single atomic operation using the send: true flag.
 */
export function sendBroadcastOutput(args: SendBroadcastOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SendBroadcastResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("resend:index:sendBroadcast", {
        "from": args.from,
        "html": args.html,
        "name": args.name,
        "previewText": args.previewText,
        "replyTo": args.replyTo,
        "scheduledAt": args.scheduledAt,
        "segmentId": args.segmentId,
        "subject": args.subject,
        "text": args.text,
        "topicId": args.topicId,
    }, opts);
}

export interface SendBroadcastOutputArgs {
    /**
     * The sender email address. Must be a verified domain.
     */
    from: pulumi.Input<string>;
    /**
     * The HTML body of the broadcast email.
     */
    html?: pulumi.Input<string>;
    /**
     * An optional name for the broadcast (for internal reference).
     */
    name?: pulumi.Input<string>;
    /**
     * Preview text shown in email clients before opening the email.
     */
    previewText?: pulumi.Input<string>;
    /**
     * List of reply-to email addresses.
     */
    replyTo?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * ISO 8601 timestamp to schedule the broadcast for future delivery. Omit for immediate send.
     */
    scheduledAt?: pulumi.Input<string>;
    /**
     * The ID of the segment to send the broadcast to.
     */
    segmentId: pulumi.Input<string>;
    /**
     * The email subject line for the broadcast.
     */
    subject: pulumi.Input<string>;
    /**
     * The plain text body of the broadcast email.
     */
    text?: pulumi.Input<string>;
    /**
     * Topic ID for managing unsubscribes.
     */
    topicId?: pulumi.Input<string>;
}
