// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Send a batch of up to 100 emails in a single API call using the Resend API. Returns an array of email IDs.
 */
export function sendBatchEmail(args: SendBatchEmailArgs, opts?: pulumi.InvokeOptions): Promise<SendBatchEmailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("resend:index:sendBatchEmail", {
        "emails": args.emails,
    }, opts);
}

export interface SendBatchEmailArgs {
    /**
     * List of emails to send (maximum 100).
     */
    emails: inputs.functions.BatchEmailRequest[];
}

export interface SendBatchEmailResult {
    /**
     * Array of results, each containing the ID of a sent email.
     */
    readonly data: outputs.functions.BatchEmailResult[];
}
/**
 * Send a batch of up to 100 emails in a single API call using the Resend API. Returns an array of email IDs.
 */
export function sendBatchEmailOutput(args: SendBatchEmailOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SendBatchEmailResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("resend:index:sendBatchEmail", {
        "emails": args.emails,
    }, opts);
}

export interface SendBatchEmailOutputArgs {
    /**
     * List of emails to send (maximum 100).
     */
    emails: pulumi.Input<pulumi.Input<inputs.functions.BatchEmailRequestArgs>[]>;
}
