// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Trigger a custom event for a contact via the Resend API. Requires exactly one of contactId or email to identify the contact.
 */
export function sendEvent(args: SendEventArgs, opts?: pulumi.InvokeOptions): Promise<SendEventResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("resend:index:sendEvent", {
        "contactId": args.contactId,
        "email": args.email,
        "event": args.event,
        "payload": args.payload,
    }, opts);
}

export interface SendEventArgs {
    /**
     * The ID of the contact to trigger the event for. Exactly one of contactId or email must be provided.
     */
    contactId?: string;
    /**
     * The email address of the contact to trigger the event for. Exactly one of contactId or email must be provided.
     */
    email?: string;
    /**
     * The name of the event to trigger (e.g., 'user.created').
     */
    event: string;
    /**
     * Optional key-value pairs of event data.
     */
    payload?: {[key: string]: any};
}

export interface SendEventResult {
    /**
     * The name of the triggered event.
     */
    readonly event: string;
}
/**
 * Trigger a custom event for a contact via the Resend API. Requires exactly one of contactId or email to identify the contact.
 */
export function sendEventOutput(args: SendEventOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<SendEventResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("resend:index:sendEvent", {
        "contactId": args.contactId,
        "email": args.email,
        "event": args.event,
        "payload": args.payload,
    }, opts);
}

export interface SendEventOutputArgs {
    /**
     * The ID of the contact to trigger the event for. Exactly one of contactId or email must be provided.
     */
    contactId?: pulumi.Input<string>;
    /**
     * The email address of the contact to trigger the event for. Exactly one of contactId or email must be provided.
     */
    email?: pulumi.Input<string>;
    /**
     * The name of the event to trigger (e.g., 'user.created').
     */
    event: pulumi.Input<string>;
    /**
     * Optional key-value pairs of event data.
     */
    payload?: pulumi.Input<{[key: string]: any}>;
}
