// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Resend email template with HTML, optional defaults, and template variables.
 */
export class Template extends pulumi.CustomResource {
    /**
     * Get an existing Template resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Template {
        return new Template(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Template';

    /**
     * Returns true if the given object is an instance of Template.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Template {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Template.__pulumiType;
    }

    /**
     * Optional template alias.
     */
    declare public readonly alias: pulumi.Output<string | undefined>;
    /**
     * Timestamp when the template was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional default sender for emails sent with the template.
     */
    declare public readonly from: pulumi.Output<string | undefined>;
    /**
     * The HTML body for the template.
     */
    declare public readonly html: pulumi.Output<string>;
    /**
     * The template name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Optional default reply-to addresses for emails sent with the template.
     */
    declare public readonly replyTo: pulumi.Output<string[] | undefined>;
    /**
     * Optional default subject for emails sent with the template.
     */
    declare public readonly subject: pulumi.Output<string | undefined>;
    /**
     * Optional plain text body for the template.
     */
    declare public readonly text: pulumi.Output<string | undefined>;
    /**
     * Timestamp when the template was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Optional template variable definitions.
     */
    declare public readonly variables: pulumi.Output<outputs.resources.TemplateVariable[] | undefined>;

    /**
     * Create a Template resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TemplateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.html === undefined && !opts.urn) {
                throw new Error("Missing required property 'html'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["alias"] = args?.alias;
            resourceInputs["from"] = args?.from;
            resourceInputs["html"] = args?.html;
            resourceInputs["name"] = args?.name;
            resourceInputs["replyTo"] = args?.replyTo;
            resourceInputs["subject"] = args?.subject;
            resourceInputs["text"] = args?.text;
            resourceInputs["variables"] = args?.variables;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        } else {
            resourceInputs["alias"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["from"] = undefined /*out*/;
            resourceInputs["html"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["replyTo"] = undefined /*out*/;
            resourceInputs["subject"] = undefined /*out*/;
            resourceInputs["text"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["variables"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Template.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Template resource.
 */
export interface TemplateArgs {
    /**
     * Optional template alias.
     */
    alias?: pulumi.Input<string>;
    /**
     * Optional default sender for emails sent with the template.
     */
    from?: pulumi.Input<string>;
    /**
     * The HTML body for the template.
     */
    html: pulumi.Input<string>;
    /**
     * The template name.
     */
    name: pulumi.Input<string>;
    /**
     * Optional default reply-to addresses for emails sent with the template.
     */
    replyTo?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Optional default subject for emails sent with the template.
     */
    subject?: pulumi.Input<string>;
    /**
     * Optional plain text body for the template.
     */
    text?: pulumi.Input<string>;
    /**
     * Optional template variable definitions.
     */
    variables?: pulumi.Input<pulumi.Input<inputs.resources.TemplateVariableArgs>[]>;
}
