// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Resend webhook endpoint that receives event notifications.
 */
export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'resend:index:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * Timestamp when the webhook was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The HTTPS URL that Resend will send webhook events to.
     */
    declare public readonly endpoint: pulumi.Output<string>;
    /**
     * List of event types to subscribe to. Valid events include email.sent, email.delivered, email.bounced, email.complained, email.opened, email.clicked, email.failed, email.delivery_delayed, email.scheduled, email.received, email.suppressed, domain.created, domain.updated, domain.deleted, contact.created, contact.updated, and contact.deleted.
     */
    declare public readonly events: pulumi.Output<string[]>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.endpoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if (args?.events === undefined && !opts.urn) {
                throw new Error("Missing required property 'events'");
            }
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["events"] = args?.events;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["events"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Webhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * The HTTPS URL that Resend will send webhook events to.
     */
    endpoint: pulumi.Input<string>;
    /**
     * List of event types to subscribe to. Valid events include email.sent, email.delivered, email.bounced, email.complained, email.opened, email.clicked, email.failed, email.delivery_delayed, email.scheduled, email.received, email.suppressed, domain.created, domain.updated, domain.deleted, contact.created, contact.updated, and contact.deleted.
     */
    events: pulumi.Input<pulumi.Input<string>[]>;
}
